@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/python.puml
!include DEVICONS/postgresql.puml
!include FONTAWESOME/users.puml


LAYOUT_WITH_LEGEND()


Container(api_1, "Api application", "Service", "Предоставляет все функции для взаимодействия с базой данных", $sprite="python")
ContainerDb(db, "Database", "PostgresSQL", "Хранит информацию о функциях, пользователях и триггерах", $sprite="msql_server")


System_Boundary(api_2, "Service run function", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(Handler, "Обработчик запросов", "Controller", "Получение запросов на вызов функций", $sprite="python")
    ContainerQueue(celery, 'Очередь заданий', 'celery', 'Выполнение задач в фоновом режиме')
    ContainerDb(db_redis, "Database", "Redis", "Служит для передачи данных", $sprite="msql_server")
}

Rel(api_1, Handler, "Использует", 'https')

Rel(Handler, db, "Читает из", 'https')

Rel_R(Handler, db_redis, "Забирает задачу из")
Rel(db_redis, celery, "Отправляет в")

Rel_L(celery, Handler, 'Уведомляет')
Rel(celery, db_redis, 'Сохраняет результат в')
@enduml
