@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/python.puml
!include DEVICONS/postgresql.puml
!include FONTAWESOME/users.puml


LAYOUT_WITH_LEGEND()

Person(user, "Пользователи", "Люди желающие запускать свои скрипты с поомщью триггеров", $sprite="users")

Container(app, "Serverless", "System", "Приложение для запуска пользовательских функций, позволяющее писать свои функции на различных языках програмирования, а так же пользоваться чужими публичными функциями. Настраивать запуск этих функций на триггеры", $sprite="React")

Person_Ext(discord, "Telegram", "Бот в Месседжере, благодаря которрому можно отправить запрос", $sprite="users")
Person_Ext(github, "Github", "Гитхаб для получения коммитов и тп", $sprite="users")
Person_Ext(api, "API", "Простая возможность запускать функции на свое усмотерние с помощью api", $sprite="users")


Rel(user, app, 'Использует')
Rel(discord, app, 'Использует')
Rel(github, app, 'Использует')
Rel(api, app, 'Использует')
@enduml
