@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/python.puml
!include DEVICONS/postgresql.puml
!include FONTAWESOME/users.puml


LAYOUT_WITH_LEGEND()

Person(user_auth, "Зарегестрированные пользователи", "Люди имеют аккаунт в сервисе", $sprite="users")
Person(user_not_auth, "Незарегестрированные пользователи", "Люди не имеют аккаунта в сервисе", $sprite="users")
Person(admin, "Администратор", "Следит за системой, добавляет обЪеты в бд по необходимости", $sprite="users")

Person_Ext(discord, "Telegram", "Бот в Месседжере, благодаря которрому можно отправить запрос", $sprite="users")
Person_Ext(github, "Github", "Гитхаб для получения коммитов и тп", $sprite="users")
Person_Ext(api, "API", "Простая возможность запускать функции на свое усмотерние с помощью api", $sprite="users")

System_Boundary(main_app, "Servcerless"){
    Container(spa, "SPA", "ReactTS", "Основной интерфейс, с которым взаимодействует клиент", $sprite="React")
    Container(api_1, "Api application", "Service", "Предоставляет все функции для взаимодействия с базой данных", $sprite="python")
    
    ContainerDb(db, "Database", "PostgresSQL", "Хранит информацию о функциях, пользователях и триггерах", $sprite="msql_server")

    Container(api_2, "Service run function", "Service", "Сервис запуска пользовательских функций", $sprite="python")
    Container(auth, "Service Authorizations", "Service", "Сервис Регистрации/авторизации пользователя", $sprite="python")
    Container(ide, "Service write function", "Service", "Сервис Для написания и тестирования функций", $sprite="python")
    Container(function, "Service find function", "Service", "Сервис для поиска функций", $sprite="python")
    Container(trigger, "Service workspace", "Service", "Сервис объединения функций и способов их запуска", $sprite="python")
}


Rel(user_auth, spa, 'Используют')
Rel(user_not_auth, spa, 'Используют')
Rel(admin, spa, 'Используют')

Rel(spa, api_1, 'Использует')

Rel(discord, api_1, 'Используют')
Rel(github, api_1, 'Используют')
Rel(api, api_1, 'Используют')

Rel(api_1, api_2, 'Использует')
Rel(api_1, auth, 'Использует')
Rel(api_1, ide, 'Использует')
Rel(api_1, function, 'Использует')
Rel(api_1, trigger, 'Использует')

Rel(api_2, db, 'Чтение из /Загрузка в')
Rel(auth, db, 'Чтение из /Загрузка в')
Rel(ide, db, 'Чтение из /Загрузка в')
Rel(function, db, 'Чтение из /Загрузка в')
Rel(trigger, db, 'Чтение из /Загрузка в')
@enduml
