@startuml
hide empty description

state "WorkSpace Создан" as WorkSpace_1
state "Поле триггер функция создана" as WorkSpace_2
state "Функция указана" as WorkSpace_3
state "Триггер и функция объединены " as WorkSpace_4
state "WorkSpace создан полностью" as WorkSpace_5

WorkSpace_1 --> WorkSpace_2
WorkSpace_2 --> WorkSpace_3 : Желаемая функция присутствует
WorkSpace_3 --> WorkSpace_4 : Указал триггер для активации
WorkSpace_4 --> WorkSpace_5 : [нажал кнопку сохранить]

state "Выбор способа" as ide
state "Перешел в IDE" as ide_1
state "Поиск функций в библиотеке" as ide_2
state "Процесс написания функции" as ide_3
state "Сохранил функцию" as ide_4
state "Тестирование и отладка" as ide_5

ide --> ide_1 : [Решил написать сам]
ide --> ide_2: [Решил найти функцию]
ide_1 --> ide_3 

ide_2 --> ide_3 : [Решил изменить]
ide_3 --> ide_4 : Нажал на кнопку сохранить

ide_3 -> ide_5
ide_5 -> ide_3 

state "WorkSpace ждет активации" as wait
state "WorkSpace запустился" as wait_1
state "WorkSpace Отдал результат" as wait_2

wait -> wait_1 : Поступил триггер
wait_1 -> wait_2 : Функции выполнелись
wait_2  --> wait


WorkSpace_5 --> wait : [Сохранен в бд]
WorkSpace_2 -> ide : Желаемая функция отсутствует
ide_4 --> WorkSpace_3 : Создана
ide_2 -> WorkSpace_3 : Выбрал подходящую
@enduml
